### ISSUE TITLE
Disable widescreen error - unexpected '('

### ISSUE THREAD

**Issue by BostonDanPhD** [shmykelsa/AA-Tweaker#1]
When I press disable widescreen on V1.4, I get an error

/system/bin/sh: stdin[1] unexpected '('

Hence widescreen is still forced on the display.

**Comment by shmykelsa** [comment]
Thanks for this.

It will be addressed in the next update. 

Nevertheless, if your goal is to revert widescreen being forced (on a non-widescreen car) you should be able to do so by first applying "Enable Force Widescreen" and then pressing it again. It should clear the database with the flags that force widescreen mode.

**Comment by BostonDanPhD** [comment]
Smrykelsa,

This also applies to enable widescreen. For now I reverted to v1.3 to apply, and then upgrade back to v1.4.

Great work, btw. I love the dual screen. Wish there were an easy way to switch between widescreen and no widescreen without rebooting, as sometimes I'd like to have widescreen and sometimes I'd like dual windows.

**Comment by shmykelsa** [comment]
Fixed with V.1.5
