### ISSUE TITLE
AA-Tweaker 3.0.10and AA 6.0 not working

### ISSUE THREAD

**Issue by 22marco77** [shmykelsa/AA-Tweaker#10]
Android 10
AA v 6.6.615333 and AA AIO Tweaker v 3.0.1 the custom patch does not work, the tweak remains on apply and fails to patch the custom apps, it just continues to run with the voice I apply tweak but then nothing happens anymore no yes stop the patch attempt.

i hope i was clear sorry my inglee but a google translator

**Comment by shmykelsa** [comment]
Hi, 

You could help me out by sending me a log of when you apply the patch for the custom apps. Once you have run the patch, head over to the upper menu and select copy log, then paste it here. 

Thanks.

**Comment by 22marco77** [comment]
I would be glad to be able to do so, the only problem is that when I click
on it applies the patch it loops and remains on the writing I am applying
the twek.. I'm going to up with your picture. So I am forced to close the
application.


Il mar 23 feb 2021, 21:18 Gabriele Rizzo <notifications@github.com> ha
scritto:

**Comment by shmykelsa** [comment]
Oh okay, I didn't got that initially. I'll look into it and maybe hit you up with a debug version to see what's going on.

**Comment by shmykelsa** [comment]
It seems like this is happening because AA AIO TWEAKER cannot find a suitable method for patching the apps. While I can fix the fact that the app hangs on that loading dialog, the fact that the app cannot find a suitable method is something wront with your Google Play Services' database. Could it be that you recently deleted Google Play Services datas?

**Comment by 22marco77** [comment]
Thank you very much, if you prefer we can also communicate in Italian since
my English is translated by google. Thank you for taking an interest in my
problem

Il mar 23 feb 2021, 21:51 Gabriele Rizzo <notifications@github.com> ha
scritto:

**Comment by shmykelsa** [comment]
Certo, possiamo anche comunicare in Italiano, ma siccome i problemi possono essere di pubblico interesse, non vorrei che alcuni non capiscano.

Sure, we can comunicate in Italian language, but since a problem can be common, I don't want anyone to miss out on a possible solution.

**Comment by 22marco77** [comment]
Grazie, io mi riferivo alla corrispondenza via email, su github continuo in
inglese.
Grazie mille spero che riesca a risolvere il mio problema, altrimenti non
riesco più ad utilizzare kodi in auto.


Il mar 23 feb 2021, 22:16 Gabriele Rizzo <notifications@github.com> ha
scritto:

**Comment by 22marco77** [comment]
Okay, so let's continue in English. I hope that you will be able to resolve
this problem as soon as possible. Thank you for the work you do for us

Il mar 23 feb 2021, 22:16 Gabriele Rizzo <notifications@github.com> ha
scritto:

**Comment by shmykelsa** [comment]
The loop has been fixed with version 3.1 released today.

**Comment by 22marco77** [comment]
Thanks you.. GreatIl 26 feb 2021 21:13, Gabriele Rizzo <notifications@github.com> ha scritto:
The loop has been fixed with version 3.1 released today.
