### ISSUE TITLE
Database Google Services

### ISSUE THREAD

**Issue by begale70** [shmykelsa/AA-Tweaker#12]
![Screenshot_20210226-195425](https://user-images.githubusercontent.com/79722139/109349317-0cbb2f00-7876-11eb-94dc-1b745711dcfe.jpg)

Ho cancellato i dati da Google play Services qualche giorno fa, ho appena aggiornato il firmware del mio Oneplus 6 e ora Aio tweaker 3.1 non funziona più.

Android 10

**Comment by begale70** [comment]
REGISTRO:
REGISTRO:


-- Reverting the hack  --

-- Reverting the hack  --

-- Reverting the hack  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS after_delete;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS aa_patched_apps_fix;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS aa_patched_apps;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM FlagOverrides;'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM FlagOverrides;'
	ErrorStream:
		Error: database is locked
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM FlagOverrides;'--  Apps which will be added to whitelist: --
		- Screen2Auto (ru.inceptive.screentwoauto)


-- Drop Triggers  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DROP TRIGGER IF EXISTS aa_patched_apps; DROP TRIGGER IF EXISTS after_delete;DROP TRIGGER IF EXISTS aa_patched_apps_fix;'

--  DELETE old Flags  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM Flags WHERE name="app_white_list";'

--  run SQL method #2  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);'
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'CREATE TRIGGER aa_patched_apps AFTER DELETE
		ON Flags
		BEGIN
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", (SELECT version FROM Packages WHERE packageName="com.google.android.gms.car"), 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", 230, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		INSERT OR REPLACE INTO Flags (packageName, version, flagType, partitionId, user, name, stringVal, committed) VALUES ("com.google.android.gms.car#car_setup", 234, 0, 0, "", "app_white_list", "ru.inceptive.screentwoauto",1);
		END;
		'
--  end SQL method #2  --

--  new fix method   --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db ''
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'CREATE TRIGGER aa_patched_apps_fix AFTER DELETE
		ON FlagOverrides
		BEGIN
		END;'
	ErrorStream:
		Error: near "END": syntax error

--  Check (1/3)  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'SELECT * FROM Flags WHERE name="app_white_list";'
	InputStream:
		com.google.android.gms.car#car_setup|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car_setup|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car_setup|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1
--  Check (2/3)  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'DELETE FROM Flags WHERE name="app_white_list";'
--  Check (3/3)  --
	OutputStream:
		/data/user/0/sksa.aa.tweaker/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db 'SELECT * FROM Flags WHERE name="app_white_list";'
	InputStream:
		com.google.android.gms.car#car_setup|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car_setup|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car_setup|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car#car|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|230|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|234|0|0||app_white_list||||ru.inceptive.screentwoauto||1
		com.google.android.gms.car|247|0|0||app_white_list||||ru.inceptive.screentwoauto||1

--  Check seems OK :)  --

**Comment by shmykelsa** [comment]
Please try as follows:

- Unistall Update of Google Play Services
- Disable it
- Wipe cache of Google Play Services
- Enable it
- Update it with play store (quick link here: https://play.google.com/store/apps/details?id=com.google.android.gms&hl=it&gl=US)
- Reboot around 3 times with 5 minutes between each reboot. It will help if after each reboot you open Android Auto

WARNING: This operation might temporarily deactivate features bind to Google account such as: Google Pay cards, Location History, Account backup etc. 

This should help a force re-build of the database.

**Comment by begale70** [comment]
Ho provato fare Uninstall Update Google Play Services.

Il telefono si blocca per 1 minuto e poi si riavvia da solo: è normale ?

 

 

Da: Gabriele Rizzo <notifications@github.com> 
Inviato: venerdì 26 febbraio 2021 21:12
A: shmykelsa/AA-Tweaker <AA-Tweaker@noreply.github.com>
Cc: begale70 <alessandro.beggiato@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [shmykelsa/AA-Tweaker] Database Google Services (#12)

 

Please try as follows:

*	Unistall Update of Google Play Services
*	Disable it
*	Wipe cache of Google Play Services
*	Enable it
*	Update it with play store (quick link here: https://play.google.com/store/apps/details?id=com.google.android.gms <https://play.google.com/store/apps/details?id=com.google.android.gms&hl=it&gl=US> &hl=it&gl=US)
*	Reboot around 3 times with 5 minutes between each reboot. It will help if after each reboot you open Android Auto

WARNING: This operation might temporarily deactivate features bind to Google account such as: Google Pay cards, Location History, Account backup etc.

This should help a force re-build of the database.

**Comment by shmykelsa** [comment]
> Ho provato fare Uninstall Update Google Play Services. Il telefono si blocca per 1 minuto e poi si riavvia da solo: è normale ? 

First of all, please keep the language in English. Not everyone understands Italian and your problem might be helpful for someone else.

About the phone freezing, that's not normal behaviour.

**Comment by begale70** [comment]
I was able to uninstall the updates and clear the cache. Now I do the 3 reboots as indicated and let you know.

Thank you

 

 

Da: Gabriele Rizzo <notifications@github.com> 
Inviato: venerdì 26 febbraio 2021 21:37
A: shmykelsa/AA-Tweaker <AA-Tweaker@noreply.github.com>
Cc: begale70 <alessandro.beggiato@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [shmykelsa/AA-Tweaker] Database Google Services (#12)

 

Ho provato fare Uninstall Update Google Play Services. Il telefono si blocca per 1 minuto e poi si riavvia da solo: è normale ?

First of all, please keep the language in English. Not everyone understands Italian and your problem might be helpful for someone else.

About the phone freezing, that's not normal behaviour.

**Comment by begale70** [comment]
I was successful, now AA AIO TWEACKER is working correctly.

Thanks so much

 

 

Da: Gabriele Rizzo <notifications@github.com> 
Inviato: venerdì 26 febbraio 2021 21:37
A: shmykelsa/AA-Tweaker <AA-Tweaker@noreply.github.com>
Cc: begale70 <alessandro.beggiato@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [shmykelsa/AA-Tweaker] Database Google Services (#12)

 

Ho provato fare Uninstall Update Google Play Services. Il telefono si blocca per 1 minuto e poi si riavvia da solo: è normale ?

First of all, please keep the language in English. Not everyone understands Italian and your problem might be helpful for someone else.

About the phone freezing, that's not normal behaviour.

**Comment by Garfield69117** [comment]
> Please try as follows:
> 
> * Unistall Update of Google Play Services
> * Remove Google Device Manager from admin rights in settings
> * Disable it
> * Wipe cache of Google Play Services
> * Enable it
> * Update it with play store (quick link here: https://play.google.com/store/apps/details?id=com.google.android.gms&hl=it&gl=US)
> * Reboot around 3 times with 5 minutes between each reboot. It will help if after each reboot you open Android Auto
> * Optional: reactivate Google Device Manager in admin rights in settings
> 
> WARNING: This operation might temporarily deactivate features bind to Google account such as: Google Pay cards, Location History, Account backup etc.
> 
> This should help a force re-build of the database.

Works great, many thanks!
