### ISSUE TITLE
Disconnect second Phone.

### ISSUE THREAD

**Issue by moare01** [shmykelsa/AA-Tweaker#2]
Hello,

Disable Bluetooth auto connect works great with Samsung S6 Edge.
But my primary Phone is Bluetooth disconnected from the Head Unit (VW Discover Pro 2018) when connected via USB.
Can you develop a new Feature to clone another Phone?

**Comment by shmykelsa** [comment]
Connencting to another phone is solely headunit's responsibility. Plus, the phone you would like to connect is not running Android Auto, so this issue has nothing to do with AA AIO TWEAKER.

**Comment by moare01** [comment]
You are right.
Hence my question whether it is designed to use the information of another phone.
Sorry, this is not an issue.
