### ISSUE TITLE
Block "navigation is active" flag

### ISSUE THREAD

**Issue by andrewleech** [shmykelsa/AA-Tweaker#3]
This is a great project, thanks for your efforts!

I don't suppose you've got any idea / seen anything that might work to block the "navigation is active" flag/mode in Android Auto that kills a car built in nav when you start navigation on Android Auto?

I've got a VW with a digital dash which can normally show maps on the dash, but if you start navigation in Android Auto (any nav app) this gets disabled - it'd be great to stop this happening!

**Comment by shmykelsa** [comment]
@andrewleech Probably this won't be possible via AA AIO TWEAKER. That is car software that is deciding what to show. I could double check, but I don't think I've ever saw a flag that reports the status of navigation within Android Auto.

**Comment by andrewleech** [comment]
Cheers, yeah I've been trying to stop this behaviour from the car side, but there doesn't seem to be any obd/coding settings to disable it on my car. 

I just thought you're clearly fairly knowledgeable about hidden settings from the phone side that it'd be worth an ask.

I've done quite a bit of phone app patching with dexpatcher in the past, I might have a go at fixing it that way when I get a chance!

**Comment by shmykelsa** [comment]
@andrewleech Could you please attach a photo of how the navigator looks on the cluster display?

**Comment by andrewleech** [comment]
I've got the VW digital dash which shows the built in nav in the dash, I think it's the best feature of the car.
https://www.google.com/search?q=vw+active+info+display+navigation&prmd=visn&sxsrf=ALeKk03wqZQstoo7UQBbimDhCeUP5NTcUw:1609365980781&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiy8uO82_btAhV3gtgFHTZ6B68Q_AUoAnoECAMQAg&biw=360&bih=560

This discussion about trying to fix the same issue from the car side also has a couple of images: https://github.com/jilleb/mib2-toolbox/issues/10

**Comment by shmykelsa** [comment]
@andrewleech I see only pictures of the stock navigation in that thread. Could you please attach a demo picture so I can understand better?

**Comment by andrewleech** [comment]
Sorry I thought that's what you meant.
That's all it ever has, the car does not support Android Auto or anything else in the dash, just on the main screen. I'm happy enough with that.

When you plug in phone and start Android Auto, it will jump to Google maps on main screen but leave the stock map on the dash - this is great because I like the map on dash to glance at to see what corners are coming up etc.

However, if you then start navigation on Google maps (or any other AA nav app) then the dash loses its map display and just shows the text "Smartphone navigation is currently active". This is what I'd like to remove to allow it to still show (stock) map on dash while AA is navigating.

**Comment by shmykelsa** [comment]
If it's like that there's nothing I can really do. If there were actual indications I could have found a potential way to block this behavior. But not like this
