### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marc2264** [shmykelsa/AA-Tweaker#37]
What can I do? I don't want to load the patch, it says that I have to wait but I'm waiting two days if there is any solution

**Comment by shmykelsa** [comment]
I'm sorry, what patch you don't want to load? What version of AA AIO TWEAKER are you using? Who told you to wait?

**Comment by marc2264** [comment]
I want to load aa mirror to android auto application number 4.0.2 with application 4.0.1 I can't even run. I have android 6.0 on samsung 
 
 
  Dnia śr., kwi 28, 2021 o 21:40, Gabriele ***@***.***> napisał:   


I'm sorry, what patch you don't want to load? What version of AA AIO TWEAKER are you using? Who told you to wait?

**Comment by marc2264** [comment]
I want to load aa mirror to android auto application number 4.0.2 with application 4.0.1 I can't even run. I have android 6.0 on samsung s5


 
 
  Dnia śr., kwi 28, 2021 o 21:40, Gabriele ***@***.***> napisał:   


I'm sorry, what patch you don't want to load? What version of AA AIO TWEAKER are you using? Who told you to wait?

**Comment by marc2264** [comment]
Hello, I have already solved the problem with the application for the fifth time, after removing and reinstalling it, I have one more issue whether on android 5.0.1 this application also works as well, which number. Regards


 
 
  Dnia śr., kwi 28, 2021 o 21:40, Gabriele ***@***.***> napisał:   


I'm sorry, what patch you don't want to load? What version of AA AIO TWEAKER are you using? Who told you to wait?

**Comment by shmykelsa** [comment]
Given that Android Auto will not work anymore on devices with Android 5.x, AA AIO TWEAKER is not compatible with that Android version.

**Comment by marc2264** [comment]
😢👍👋 
 
  Dnia czw., kwi 29, 2021 o 10:10, Gabriele ***@***.***> napisał:   


Given that Android Auto will not work anymore on devices with Android 5.x, AA AIO TWEAKER is not compatible with that Android version.
