### ISSUE TITLE
Problem in aa aio tweaker 

### ISSUE THREAD

**Issue by turky89** [shmykelsa/AA-Tweaker#38]
I try to open aa aio tweaker and everytime i opened it it shows a message that it can't find any acount in google play services and refuse to patch any prog 
Note :everything is installed and ok

**Comment by IJK-CZ** [comment]
Exactly the same problem.... Android 11, Xiaomi MI 11 lite, MIUI12.5, magisk V23.

**Comment by shmykelsa** [comment]
Fixed as account system is now dropped
