### ISSUE TITLE
Allow opening Google Maps while connected

### ISSUE THREAD

**Issue by cgarz** [shmykelsa/AA-Tweaker#39]
Would it be possible to remove the restriction on opening Google Maps while plugged in?

Unless I'm blind and this is already possible. Though I can't find an option that looks like it would allow it.

Whenever I try to open it it just says:
"Your phone can't display Google Maps while Android Auto is running"

Even when I'm just responding to it asking me to rate a place or something. Being asked a question and then not being allowed to answer is quite annoying 😆

**Comment by mikecharles** [comment]
Hey, do you have any thoughts on this? Is this possible?

**Comment by Beat-YT** [comment]
Would love to see this.

**Comment by shmykelsa** [comment]
This used to be a thing with 2 or 3 Android Auto versions but they eventually dropped it. If they add it again it will be back to AIO TWEAKER
