### ISSUE TITLE
Independent night mode option doesn't work anymore

### ISSUE THREAD

**Issue by lukjod** [shmykelsa/AA-Tweaker#41]
After switch to newest AA on Android 11, after switch on independent night mode and set control by phone it stays always on day not Metter which mode is set on the phone. Must manually always change in AA. Eaer it was working great so google must change something recently![Screenshot_20210626-221725_Android Auto.jpg](https://user-images.githubusercontent.com/1781446/123524822-0bd3c600-d6cd-11eb-8369-6382cac81bdf.jpg)

**Comment by shmykelsa** [comment]
Deprecated
