### ISSUE TITLE
You cannot restrict redistribution of a GPLv2 work.

### ISSUE THREAD

**Issue by Overwatching** [shmykelsa/AA-Tweaker#43]
Just an FYI.

In your [readme](https://github.com/shmykelsa/AA-Tweaker#no-reuploads) you state...
"...Any unauthorized re-upload of the APK, in any way, will result in a DMCA takedown request."

Your work is a fork of a GPLv2 work which means it must also be GPLv2 (it is labeled properly). This means that you cannot restrict redistribution of the work, or its source in any way. That means that everyone is ALREADY "authorized" upload it elsewhere.

Anyone can (re)distribute any GPLv2 work. With or without modifications.

I agree that people SHOULD be pointed here to get releases. But there is literally nothing you can do about it.
(In fact, the submission of a DMCA takedown would itself be illegal.)

So, you should probably just change that section to politely ask people to point to this repository.

**Comment by shmykelsa** [comment]
Thanks for the head up!

**Comment by shmykelsa** [comment]
Addressed with commit [35f4a08](https://github.com/shmykelsa/AA-Tweaker/commit/35f4a081277632a2325892e1fc959d0a21eb2674)
