### ISSUE TITLE
MultiDisplay Crashes

### ISSUE THREAD

**Issue by Hav-Laz** [shmykelsa/AA-Tweaker#44]
when enabling, the option apeers in AA at the car, but when enabling, the screen gets black (after next startup) and the get back to AA i need to  disable MultiDisplay at the AA-Tweaker app. 
tried both option, horizon and verticle options. 

Android Auto 6.6.6125
Xiaomi mi 10T pro
android ver 11

**Comment by shmykelsa** [comment]
Are you sure you are not talking about Extras For AA?

**Comment by Hav-Laz** [comment]
no.. AA TWEAKER
![IMG_20210805_114227](https://user-images.githubusercontent.com/88480013/128320430-0bf311fd-e530-4f8b-82af-5682fc49a785.jpg)

**Comment by shmykelsa** [comment]
You are talking about vertical and horizontal. Are those options from Substratum?
