### ISSUE TITLE
AA tweeker cannot identity Google account

### ISSUE THREAD

**Issue by IJK-CZ** [shmykelsa/AA-Tweaker#45]
Any attempt to use AAT report, that ATT cannot identity Google account. The Google Play account way used all the time the phone Is used without change. Android11, MIUI 12.5, Xiaomi MI 11 lite. Following patch attempt Is unsuccessfull. Root AAT via Magisk 23.

**Comment by casta** [comment]
Hello,

Indeed, I’m facing the same issue. I try to use AA without google account (GMS are not connected to any google account, install AA using AuroraStore). But settings have no effect.


It seems that all request are built using this: `SELECT DISTINCT user FROM ApplicationTags WHERE user != ""`, which forbids settings with no account.


It would be nice to remove this limitation

**Comment by Emporea** [comment]
I am facung the same issue. Why is a Google Account requiered? @shmykelsa

**Comment by raleik-pl** [comment]
Same issue here! AiO Tweaker 5.0.2, AA 7.2.60124 and Magisk 24.1. It lets me choose from my 3 accounts I use, then it says no account was found.
I tried the "experimental" use all accounts option. It warns about apps crashing and indeed - some like whatsapp or spotify gor even removed!

**Comment by AngelDark92** [comment]
Same problem with me too, I also have 3 accounts and it won't let me use anything but experimental, and even that does not work properly.
