### ISSUE TITLE
AA always start with Maps

### ISSUE THREAD

**Issue by Fireqc** [shmykelsa/AA-Tweaker#46]
So even with the option disable navigation at start, when I connect it it starts in Maps..
using;
AA AIO Tweaker V4.0.2
AA 6.7.612933

**Comment by Coyenzo** [comment]
There's a (new) record in the flags database called SystemUi__custom_startup_app_enabled. If you set the boolval of this record to 1, a new option in the settings inside AA appears, where you can choose wether you'd like AA to start up with the last navigation app, last media app or start menu.

**Comment by shmykelsa** [comment]
> There's a (new) record in the flags database called SystemUi__custom_startup_app_enabled. If you set the boolval of this record to 1, a new option in the settings inside AA appears, where you can choose wether you'd like AA to start up with the last navigation app, last media app or start menu.

Thanks for the tip, I am aware of that. That new flag will actually deprecate the old one in next update.

**Comment by shmykelsa** [comment]
Deprecated
