### ISSUE TITLE
App Closes after pressing the accept button

### ISSUE THREAD

**Issue by skisys** [shmykelsa/AA-Tweaker#48]
Hello,
Sadly my App closes directly after pressing the accept button.
I tried installing older versions of this app as well, but it didn't help.

I have a Samsung Tab 3 (10.1) and it runs on Android Version 6 (CyanogenMod 13.0-20160321-Unoffical-santos10lte)
TWRP is in use.
I even got SuperSu for the superuser quallifications.

**Comment by fcaronte** [comment]
I'm try on an old samsung s7 with lineage os 19 with android 12 and to try fix android auto app with custom app i'll try this app but same for me after gain root, reboot, and press accept app is close with this error

`2021-12-03 19:31:47.567 8832-8832/sksa.aa.tweaker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sksa.aa.tweaker, PID: 8832
    java.lang.RuntimeException: Unable to start activity ComponentInfo{sksa.aa.tweaker/sksa.aa.tweaker.MainActivity}: java.lang.NumberFormatException: For input string: ""
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.parseInt(Integer.java:650)
        at sksa.aa.tweaker.MainActivity.onCreate(Unknown Source:74)
        at android.app.Activity.performCreate(Activity.java:8051)
        at android.app.Activity.performCreate(Activity.java:8031)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)`

**Comment by roman1990** [comment]
Having the same issue

**Comment by nikolowry** [comment]
Can anyone provide the schema of `phenotype.db` for a MicroG user? I was able to create the ApplicationTags table with dummy row data to launch -- but now most of the commands don't work because none of those tables exist.

If I figure it out I'll dump them here later

**Comment by arcane47** [comment]
> Can anyone provide the schema of `phenotype.db` for a MicroG user? I was able to create the ApplicationTags table with dummy row data to launch -- but now most of the commands don't work because none of those tables exist.
> 
> If I figure it out I'll dump them here later

Figure it out?

**Comment by nikolowry** [comment]
> > Can anyone provide the schema of `phenotype.db` for a MicroG user? I was able to create the ApplicationTags table with dummy row data to launch -- but now most of the commands don't work because none of those tables exist.
> > If I figure it out I'll dump them here later
> 
> Figure it out?

I haven't had any free time since posting that, but am hoping that within the next month I'll be able to spend an afternoon tinkering.

**Comment by Rikj000** [comment]
> Can anyone provide the schema of `phenotype.db` for a MicroG user? I was able to create the ApplicationTags table with dummy row data to launch -- but now most of the commands don't work because none of those tables exist.
> 
> If I figure it out I'll dump them here later

MicroG appears to not use the `phenotype.db` for anything,
since the file didn't exist on all 3 of my physical devices.

I've managed to generate / use a "vanilla" `phenotype.db` file as following:
1. Android Studio -> Device Manager -> Create Android 13 x86_64 (Target Google APIs) AVD (Android Virtual Device)
2. Root the AVD with [rootAVD](https://github.com/newbit1/rootAVD)
3. Copy the `/data/data/com.google.android.gms/databases/phenotype.db` from the AVD to your phone
4. Force Stop Android Auto + Clear it's cache + reboot

Took an initial backup + another once I've noticed that the file grew in size after a day or so of using the AVD:
- [phenotype-vanilla.db.txt](https://github.com/shmykelsa/AA-Tweaker/files/11072427/phenotype-vanilla.db.txt)
- [phenotype-vanilla-updated.db.txt](https://github.com/shmykelsa/AA-Tweaker/files/11072425/phenotype-vanilla-updated.db.txt)
*(Remove the `.txt` suffix, Github otherwise didn't allow the uploads of the `.db` files)*

Using this `.db` file helped with getting Android Auto / Waze / 3th party apps working correctly.   
All, excluding CoolWalk appears to be working as it should now!

Though I think these `.db` files might still be missing some flags / settings.
*(Due to CoolWalk is still not working on my setup, even though the corresponding AA AIO Tweaker patch has been applied)*.

**Comment by nikolowry** [comment]
> > Can anyone provide the schema of `phenotype.db` for a MicroG user? I was able to create the ApplicationTags table with dummy row data to launch -- but now most of the commands don't work because none of those tables exist.
> > If I figure it out I'll dump them here later
> 
> MicroG appears to not use the `phenotype.db` for anything, since the file didn't exist on all 3 of my physical devices.
> 
> I've managed to generate / use a "vanilla" `phenotype.db` file as following:
> 
> 1. Android Studio -> Device Manager -> Create Android 13 x86_64 (Target Google APIs) AVD (Android Virtual Device)
> 2. Root the AVD with [rootAVD](https://github.com/newbit1/rootAVD)
> 3. Copy the `/data/data/com.google.android.gms/databases/phenotype.db` from the AVD to your phone
> 4. Force Stop Android Auto + Clear it's cache + reboot
> 
> Took an initial backup + another once I've noticed that the file grew in size after a day or so of using the AVD:
> 
> * [phenotype-vanilla.db.txt](https://github.com/shmykelsa/AA-Tweaker/files/11072427/phenotype-vanilla.db.txt)
> * [phenotype-vanilla-updated.db.txt](https://github.com/shmykelsa/AA-Tweaker/files/11072425/phenotype-vanilla-updated.db.txt)
>   _(Remove the `.txt` suffix, Github otherwise didn't allow the uploads of the `.db` files)_
> 
> Using this `.db` file helped with getting Android Auto / Waze / 3th party apps working correctly. All, excluding CoolWalk appears to be working as it should now!
> 
> Though I think these `.db` files might still be missing some flags / settings. _(Due to CoolWalk is still not working on my setup, even though the corresponding AA AIO Tweaker patch has been applied)_.

That's awesome! I ended up being able to get around limitations with my Headunit so never revisited this. Thanks for seeing it through.

**Comment by Rikj000** [comment]
> That's awesome! I ended up being able to get around limitations with my Headunit so never revisited this. 
> Thanks for seeing it through.

Managed to get CoolWalk working! 🎉 
Check out the [`v0.4-a13`](https://github.com/Rikj000/AndroidAuto4MicroG/releases/tag/v0.4-a13) release of [my fork of `aa4mg`](https://github.com/Rikj000/AndroidAuto4MicroG).
   
It contains an even more complete `phenotype.db`, pre-patched with AA-Tweaker.   
Together with an additional `com.google.android.projection.gearhead.pb` file,
which was the missing piece to the puzzle of making CoolWalk working on MicroG.
