### ISSUE TITLE
After Google service update aa mirror patch doesn't work

### ISSUE THREAD

**Issue by ellenamatteo** [shmykelsa/AA-Tweaker#49]
After Google service update aa mirror patch doesn't work.
I cannot unblock aa mirror app or personalize aa.
AA Vers 7.0

**Comment by cityfammer** [comment]
This is also the case with me. At present, I can only downgrade Android Auto to below version 6.9. 
Hope to upgrade it as soon as possible. TKS.

**Comment by zapaantonio** [comment]
My same case, although I change the AA and Google apps to the November versions, when I start AA everything works again, Screen2Auto, CarStrem, etc, but when I disconnect AA and reconnect it no longer works.

**Comment by mixalbl4-127** [comment]
+1
@shmykelsa please help

**Comment by Ojayyy** [comment]
> +1 @shmykelsa please help

+1

**Comment by technodrome** [comment]
Is there someone actually maintaining this repo? Have the same problem.

**Comment by leranp** [comment]
Same here

**Comment by mixalbl4-127** [comment]
Solution for me: https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826
@shmykelsa

**Comment by technodrome** [comment]
> Solution for me: https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826 @shmykelsa
> 
> Upd: Android Auto added some apps to black list, but you can change app ID with Lucky Patcher and it works fine!

It doesn't, so stop spreading nonsense. What you posted is
1. in Russian which very few people can understand here 
2. only applicable for a small amount of applications, if any
3. a temporary solution which does not solve the problem.

I have a feeling the author is interested only in his other paid app so I am curious if he actually finds time to update this one. Too bad.

**Comment by rq1025330** [comment]
> 我的解决方案：[https: ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)//4pda.to/forum/index.php [? ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)showtopic [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)651767 [& ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)st [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) 5320#entry106627826 @shmykelsa
> 
> 更新：Android Auto 将一些应用程序添加到黑名单，但您可以使用 Lucky Patcher 更改应用程序 ID，并且效果很好！

Screen2auto still does not work when using the apk installation package, can you?

**Comment by mixalbl4-127** [comment]
> > 我的解决方案：[https: ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)//4pda.to/forum/index.php [? ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)showtopic [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)651767 [& ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)st [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) 5320#entry106627826 @shmykelsa
> > 更新：Android Auto 将一些应用程序添加到黑名单，但您可以使用 Lucky Patcher 更改应用程序 ID，并且效果很好！
> 
> Screen2auto still does not work when using the apk installation package, can you?

Screen2auto works fine for me. Ok, for you and @technodrome simple faq in english:
1. Install lucky patcher
2. Install Screen2auto for exmaple
3. Run lucky patcher, find Screen2auto, click => Tools => Create CLONE (first option), use defaut clone options
4. Install clone
5. Remove ORIGINAL (not cloned app). P.S. Cloned APP has different last char in ID.
6. Download changeInstaller.apk from here https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826 p.s. **for downloading you have to be registered** or you get 404 error
7. Run changeInstaller. find our Cloned Screen2auto, select it and click START
8. Go to AA-Tweaker, find Cloned Screen2auto, enable as always.
9. Reboot and enjoy :)

p.s. maybe it can work without changeInstaller but I did it with this app and nas no problem.

**Comment by rq1025330** [comment]
> > > 我的解决方案：[HTTPS：](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) //4pda.to/forum/index.php [？](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)showtopic [=](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) 651767 [&](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) st [=](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) 5320#entry106627826 @shmykelsa
> > > 更新：Android Auto 将一些应用程序添加到黑名单，但您可以使用 Lucky Patcher 更改应用程序 ID，并且效果很好！
> > 
> > 
> > 使用apk安装包时Screen2auto还是不行，可以吗？
> 
> Screen2auto 对我来说很好用。好的，对于您和@technodrome简单的英文常见问题解答：
> 
> 1. 安装幸运补丁
> 2. 安装 Screen2auto 为例
> 3. 运行lucky patcher，找到Screen2auto，点击=> Tools => Create CLONE（第一个选项），使用defaut clone选项
> 4. 安装克隆
> 5. 删除 ORIGINAL（不是克隆的应用程序）。PS 克隆的应用程序在 ID 中具有不同的最后一个字符。
> 6. 从这里下载changeInstaller.apk https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826 ps**下载你必须注册**否则你会得到404错误
> 7. 运行更改安装程序。找到我们的Cloned Screen2auto，选择它并点击开始
> 8. 转到AA-Tweaker，找到Cloned Screen2auto，一如既往地启用。
> 9. 重新启动并享受:)
> 
> ps 也许它可以在没有 changeInstaller 的情况下工作，但我用这个应用程序做到了，没有问题。

Thanks!

**Comment by rq1025330** [comment]
> > > 我的解决方案：[https: ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)//4pda.to/forum/index.php [? ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)showtopic [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)651767 [& ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826)st [= ](https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826) 5320#entry106627826 @shmykelsa
> > > 更新：Android Auto 将一些应用程序添加到黑名单，但您可以使用 Lucky Patcher 更改应用程序 ID，并且效果很好！
> > 
> > 
> > Screen2auto still does not work when using the apk installation package, can you?
> 
> Screen2auto works fine for me. Ok, for you and @technodrome simple faq in english:
> 
> 1. Install lucky patcher
> 2. Install Screen2auto for exmaple
> 3. Run lucky patcher, find Screen2auto, click => Tools => Create CLONE (first option), use defaut clone options
> 4. Install clone
> 5. Remove ORIGINAL (not cloned app). P.S. Cloned APP has different last char in ID.
> 6. Download changeInstaller.apk from here https://4pda.to/forum/index.php?showtopic=651767&st=5320#entry106627826 p.s. **for downloading you have to be registered** or you get 404 error
> 7. Run changeInstaller. find our Cloned Screen2auto, select it and click START
> 8. Go to AA-Tweaker, find Cloned Screen2auto, enable as always.
> 9. Reboot and enjoy :)
> 
> p.s. maybe it can work without changeInstaller but I did it with this app and nas no problem.

Thanks!
