### ISSUE TITLE
AA versión 7.1.6!!!

### ISSUE THREAD

**Issue by mgeguren** [shmykelsa/AA-Tweaker#50]
Patching any app, be it a mirror or another, no longer works in AA version 7.1.6, do you have a solution? I tried to go back to AA 6.9 but when trying to work the app says to update or not work ...

**Comment by titopepecharls** [comment]
I have successfully patched the latest version of Screen2Auto (Screen2Auto installed from AAEase for random package name) using Android Auto 7.0.614174. This one does not require updating to work. Hope it helps.

**Comment by flyoffacliff** [comment]
Same issue here. Android 12 on a pixel 5.

My music apps like Pandora and Spotify were not installed through the Play store so they won't work with Android auto for some stupid reason. This app was able to patch them in as a workaround before. Which is arguably the most important feature of this app.

It broke on Android auto 7.1. I had to downgrade to 7.0 to fix this. Cuz this app is no longer being maintained, I'm hoping someone forks it or finds a workaround soon. Can't stay on an old version of Android Auto forever.

**Comment by leranp** [comment]
Same here with Android 12 and AA 7.1.6.
The patch make my phone freeze and then restart 
Samsung S20 FE

**Comment by chuppito** [comment]
It was a very good application. Too bad the developer no longer updates it
