### ISSUE TITLE
Release a new release

### ISSUE THREAD

**Issue by M4TH1EU** [shmykelsa/AA-Tweaker#52]
Hi, there's been quite a lot of commits and recently somes that solve an issue with Android 12, I tried building it myself but i've been trying to solve gradle issue for the past 3+ hours and it's to starting to annoy me.
Could you please publish an APK based on the current commits ?

Thanks

**Comment by leranp** [comment]
Same here

**Comment by flyoffacliff** [comment]
My boyfriend was able to get it compiled to an APK. Had to create a new API key for Pastebin or something. Not sure if he incremented the version number, and it's an unsigned copy, so you may need to uninstall the old version first.
I haven't tested it yet so the usual “don't blame me if it breaks” warning applies here. Please let us know whether it works though.
[
[AA-AIO-TWEAKER-4.0.1-debug.zip](https://github.com/shmykelsa/AA-Tweaker/files/7930602/AA-AIO-TWEAKER-4.0.1-debug.zip)
](url)

**Comment by M4TH1EU** [comment]
> My boyfriend was able to get it compiled to an APK. Had to create a new API key for Pastebin or something. Not sure if he incremented the version number, and it's an unsigned copy, so you may need to uninstall the old version first. I haven't tested it yet so the usual “don't blame me if it breaks” warning applies here. Please let us know whether it works though.
> 
> [AA-AIO-TWEAKER-4.0.1-debug.zip](https://github.com/shmykelsa/AA-Tweaker/files/7930602/AA-AIO-TWEAKER-4.0.1-debug.zip)

Thank you, seems to works just fine on Android 12 for me, if the owner could release an official build it would be even better.
