### ISSUE TITLE
Error on 5.0.1 and 5.0.2: no account found in Google services  db

### ISSUE THREAD

**Issue by woody4165** [shmykelsa/AA-Tweaker#54]
Hi
 I'm getting this error on 5.0.1
I was not getting on 5.0.0 and prior versions.

![Screenshot_2022-02-02-22-42-51-592_sksa aa tweaker](https://user-images.githubusercontent.com/6501444/152242337-c541e5f0-52e1-4814-8719-7b811a356683.jpg)

I'm not in any of the states reported in the warning list

BTW, I'm on MIUI 12.5 (Android 11) with 3 google account on phone

**Comment by gabestover** [comment]
I had the same error (in English) on both 5.0.0 and 5.0.1, and also not in any of the states on the list.  I DO have 3 Google accounts on my device.  I get this prompt when selecting any of the three. I don't get the prompt when I try the "use all accounts" option, but also none of the options work.

![Screenshot_20220202-145349_AA AIO Tweaker](https://user-images.githubusercontent.com/8377594/152251473-48386b45-ab17-4e72-95f5-cf663b8dcd7a.png)

**Comment by woody4165** [comment]
Also on 5.0.2 I'm getting same error.

**Comment by gvmiguez** [comment]
I have the same error on the V5 0.2 and since V5.0.1, the same situation as the others comments. No error on V5.0.0. 

![Screenshot_20220213-221807](https://user-images.githubusercontent.com/12910710/153775554-177ec464-edf9-4d8c-9940-d7a11dd40422.jpg)

**Comment by hayder200** [comment]
I tried all possible solutions.. clearing cache.. uninstall install reboot with different combinations. Still getting the same error (A9)

**Comment by xFaultx** [comment]
Same here, getting this error. Latest version of both AA tweaker and Android auto. Is there a specific version of Android auto i should be using?

**Comment by shmykelsa** [comment]
Please specify: 

- Do you have any custom ROM?
- If yes, which Gapps were installed?
- Google Play Services version

**Comment by woody4165** [comment]
Ciao Gabriele

No custom ROM, MIUI 12.5.14 on Redmi Note 10s with Magisk.

Google play services is on version 22.02.21

Thanks

In data 20 febbraio 2022 10:47:49 Gabriele Rizzo ***@***.***> 
ha scritto:

**Comment by Skelos** [comment]
For me Is the same. No custom rom (just rooted with magisk) on MIUI 12.5.5 on Poco X3 Pro. 

Play services : ver 21.48.15 (150400-414534850)

Thanks

**Comment by raleik-pl** [comment]
Same issue here on 5.0.2. I'm on Mi Note 10 Lite, custom rom EvolutionX Android 11, Play services are 22.06.15

**Comment by woody4165** [comment]
Same issue on Poco X3 with Lineage Os 18.1 updated to latest version.
With same 3 Google accounts as my Redmi Note 10s with stock MIUI 12.5.14 and Magisk 23
I don't see any solution

**Comment by Jon8RFC** [comment]
AA AIO 5.0.2
Pixel 6 Pro
SQ1D.220205.004
Google Play system update February 1, 2022
Play Store 29.5.14-21 [0] [PR] 430999422

**Comment by nips1900** [comment]
AA AIO 5.0.2
samsung s7
Google Play Services 22.06.15
AA 7.3.620524

**Comment by brandendeuce1** [comment]
Same here. Oneplus 8 pro, OOS stock android 11.
