### ISSUE TITLE
AA disables search bar in Waze when electronic hand brake is on

### ISSUE THREAD

**Issue by Azertixe** [shmykelsa/AA-Tweaker#58]
Hello. After weeks of searching an issue in Waze or AA updates, I recently notice that is my car's electronic hand brake that disables Waze search bar in Android Auto. That's very annoying because Google assistant is not always helpful when you search a contact address...
Favorites are disabled in same way 😤
I applied the patch for disable moviment restrictions but not working :(
I did a short video : https://drive.google.com/file/d/1_KTrenCFbF-xCM5r6Vnv7vzkkdoRRP8T/

AA AIO Tweaker 5.0.1 
AA 7.2.620123 
Waze modded 4.80.90.902 (tested with official version too)
Android 8 root on Samsung Galaxy A3 (2017)
My car : Citroën Berlingo (system version : 42.03.33.42_NAC-r0)

Thanks =)

**Comment by Azertixe** [comment]
Hello. Any solution? This problem remains with 5.0.2 😭

**Comment by shmykelsa** [comment]
Speed restriction patch is for messages preview only. Tap limitation bypass is another thing. This is intended behaviour.

**Comment by Azertixe** [comment]
Ok, is it any solution you know?

**Comment by shmykelsa** [comment]
There's simply no solution and not intended to be one

**Comment by Azertixe** [comment]
Thanks for your answer. Do tou know what is the last AA version without these restrictions ?

**Comment by shmykelsa** [comment]
@Azertixe None
