### ISSUE TITLE
Coolwalk interface

### ISSUE THREAD

**Issue by jordirs2004** [shmykelsa/AA-Tweaker#59]
Hello
I activated coolwalk interface but nothing changed
Is there anything else to do?
My phone is Poco F2 Pro
Thx

**Comment by shmykelsa** [comment]
@jordirs2004 Activate coolwalk through Android Auto settings.

**Comment by jordirs2004** [comment]
I didn't find where I can activate it in the settings...
Can you just put a screenshot please?

**Comment by okibcn** [comment]
> I didn't find where I can activate it in the settings... Can you just put a screenshot please?

Go to Settings in your car screen.
1. Go to the apps list
2. Open Settings App
3. Scroll down the settings list
4. Activate Coolwalk

**Comment by jordirs2004** [comment]
> > I didn't find where I can activate it in the settings... Can you just put a screenshot please?
> 
> Go to Settings in your car screen.
> 1. Go to the apps list
> 2. Open Settings App
> 3. Scroll down the settings list
> 4. Activate Coolwalk

Is it here? ![Screenshot_2022-02-16-20-16-03-516_com.google.android.projection.gearhead.jpg](https://user-images.githubusercontent.com/8842876/154339404-1b9c9ea6-c349-4396-9adc-12094c01c03c.jpg)

**Comment by shmykelsa** [comment]
> > > I didn't find where I can activate it in the settings... Can you just put a screenshot please?
> > 
> > 
> > Go to Settings in your car screen.
> > 
> > 1. Go to the apps list
> > 2. Open Settings App
> > 3. Scroll down the settings list
> > 4. Activate Coolwalk
> 
> Is it here? ![Screenshot_2022-02-16-20-16-03-516_com.google.android.projection.gearhead.jpg](https://user-images.githubusercontent.com/8842876/154339404-1b9c9ea6-c349-4396-9adc-12094c01c03c.jpg)

Settings have to be reached on car.

**Comment by jordirs2004** [comment]
Nothing even in the car
![MVIMG_20220220_150539_copy_1040x2312.jpg](https://user-images.githubusercontent.com/8842876/154846800-8308ccc7-9eec-411d-9de6-2656e5e20327.jpg)
![MVIMG_20220220_150600_copy_1040x2312.jpg](https://user-images.githubusercontent.com/8842876/154846807-cb57e955-b962-4817-a245-5a741fcc1fb0.jpg)

**Comment by okibcn** [comment]
It is in the car, probably Coolwalk beta feature is so far only available in English.

**Comment by rapdes** [comment]
It's not related to the system language my phone and car is all setup in English and there's no setting in the car for me either

**Comment by sas46** [comment]
Same here. Activated, no flag or changes in any of the settings

**Comment by mikecharles** [comment]
Anyone gotten this to work finally?

**Comment by shmykelsa** [comment]
Update to 5.2
