### ISSUE TITLE
Still getting 'curropted play store error'

### ISSUE THREAD

**Issue by xFaultx** [shmykelsa/AA-Tweaker#60]
It's been a week and I'm still getting the error. Flashed a new ROM and had to wipe the playstore storage, and error won't go away. If i select the experimental version the error doesn't come up, but when i install the custom apps still don't load. On a Pixel 4xl on Android 12. Before flashing there were no issues

**Comment by shmykelsa** [comment]
Not related to AA AIO TWEAKER

**Comment by xFaultx** [comment]
I'm confused, this is related to AA AIO Tweaker. When I'm using AA AIO Tweaker I would get the curropted play store error.

I figured it out, it was a combination of things that solved it, not sure which actually did it.
1. Running SELinux in permissive mode
2. Installing apps through AAEase
3. Using an older version of AA (7.2.620124)
4. Disconnecting the AAnapp from play store using detacher

So far that was the only way i could keep AA AIO Tweaker working
