### ISSUE TITLE
Patched apps are always reinstalling from scratch (data lost) and patched apps only last few hours

### ISSUE THREAD

**Issue by GMariton** [shmykelsa/AA-Tweaker#63]
Hello, 

I was using AA Tweaker 4 with the previous AA version but it stopped working a couple of days ago. 

So I eventually had to update AA (which was blocked from new updates so far) and installed AA Tweaker 5.

First surprise while I applied the patch to my common AA apps: the patching process actually reinstalls the apps from scratch and I lost some data along the way (based on the previous versions, and the fact that I didn't read anything about this new behavior, I didn't expect that my apps would be uninstalled then reinstalled) :( Nothing critical but it would have been best if I had this information before I apply the patch...

I eventually managed to get my apps working in AA again. but then after several hours, the app disappear from AA. I already applied the patch several times, I get my apps to work in AA for some time, then they disappear. 
Also, I need to tick AA in the list of patchable apps, together with Waze (a modified Waze - that's the reason I am using AA Tweaker). Obviously, every time I have to re-patch Waze, I have a new install of AA and Waze and have to go through the initial setup of AA and Waze all over again.

It's been 5 times since I installed AA Tweaker 5 yesterday, any idea of what goes wrong?

I am using AA on my OnePlus 8 Pro, OOS 11.0.10.10 rooted with Magisk, with EdXposed, PrivacyLua (no restriction on AA Tweaker) and AFWall+ (that I need to reconfigure every time I patch the app).

AA Tweaker 5.0.2
AA 7.3.620524

Thank you

**Comment by GMariton** [comment]
Upon checking, my patched Waze actually disappeared overnight without rebooting in between.

So, I am not sure what happened in between but I last used the patched Waze last evening without any issue, the next morning, the patched Waze was not available in AA anymore. No reboot, no specific changes to the phone.

**Comment by BenJewell** [comment]
I had the exact same issue, even the part with the apps being reinstalled.

I found a way to fix it. No issues in over a week now! Open Android auto on the phone and tap the build number in the app repeatedly until developer options turns on. Then go under the three dots menu in the top right and select developer settings. Then scroll down to the bottom and check the box for unknown sources.
Then you can patch it again and restart the phone. I can't remember what order so you may have to play around with it a bit.
No issues in over a week now!

**Comment by GMariton** [comment]
Thanks for the tip but even with "Unknown sources" ticked in AA, I still had to re-patch my apps from scratch (meaning patching AA and Waze again, reinstalling the apps during the patch, then setting up both AA and Waze all over again) :/

**Comment by GMariton** [comment]
Based on the last few days, I can use my patched Waze 3 times before it disappears from AA, then I have to patch again.

**Comment by aiden1989acw** [comment]
I've turned on debug logging in Android Auto and will be able to provide logs within the next couple of days.
 
I have developed a GStreamer reversing camera app that has a service that interfaces with android auto, unfortunately when the app is running on the in car head unit FPS is very slow circa 5-10 fps at most.
But when running under the emulated head unit in Android Studio it works fine.

**Comment by shmykelsa** [comment]
Update to AIO TWEAKER version 5.2
