### ISSUE TITLE
Disable widescreen at 1080p resolution

### ISSUE THREAD

**Issue by goodnews092** [shmykelsa/AA-Tweaker#64]
Hi I have confirmed that aa aio tweaker does not work with wide mode disabled tweak at 1080p resolution.  It worked for a while after enabling Tweak, but after a few hours wide mode worked and I forced it to 720P in AA developer mode so I experienced Tweak working.  Is there a way to get this to work at 1080P resolution?

**Comment by shmykelsa** [comment]
This should have been fixed with 5.2
