### ISSUE TITLE
root help

### ISSUE THREAD

**Issue by Grxffiti** [shmykelsa/AA-Tweaker#79]
Rooting my phone is confusing I don't want to wipe it, is there any way without doing all that to get this to work

**Comment by Rikj000** [comment]
> Rooting my phone is confusing I don't want to wipe it, is there any way without doing all that to get this to work

To root, you usually require a unlocked bootloader, which by default is locked.
Unlocking it will fully wipe your device, afaik no way around that.

For non root users, try installing apps through AAAD, also by @shmykelsa 
https://github.com/shmykelsa/AAAD/
