### ISSUE TITLE
AA-Tweaker and AA 6.0 not working

### ISSUE THREAD

**Issue by mattcabb** [shmykelsa/AA-Tweaker#9]
Hi! Straight to point:
I have Galaxy S10 running rooted Android10, with `Android Auto 6.0.615334-release`, AA AIO Tweaker `2.7`.
AA AIO Tweaker opens correctly with superuser prompt. Selected some apps, patched, enabled some other features as well, rebooted the phone, connected to car, and no new apps one the display.

Am I missing something or is the `Android Auto 6.0.615334-release` unsupported yet?

**Comment by shmykelsa** [comment]
It's supported.

Exactly what apps are you trying to add?

**Comment by mattcabb** [comment]
YouTube, Netflix, OBDeleven, AA-Tweaker itself.

**Comment by shmykelsa** [comment]
That's not how that tweak works.

![Screenshot_20210207-115832449.jpg](https://user-images.githubusercontent.com/9965637/107144505-d4da5f00-693b-11eb-93a9-da65517a72b6.jpg)

As clearly stated in the tutorial, the app must be specifically built for Android Auto with those libraries (whether it's unofficial or official libraries, but the latter doesn't make any sense, unless you have a play store-free device).

Each and every app you mentioned is not compatible with Android Auto, therefore making a patch for them makes no sense.

**Comment by mattcabb** [comment]
Ok, thank you for explaining. And sorry for taking you time.
